name: "Build Android APK"
on: [push, pull_request]

jobs:
  export-android:
    runs-on: ubuntu-latest
    name: Export Android APK
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Android Export
        # This action handles Godot, Templates, Java, and Android SDK automatically
        uses: dulvui/godot-android-export@v4
        with:
          godot-version: 4.4.1  # Change to your exact version
          working-directory: .   # Path to your project.godot file

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android/*.apk  # Matches the path in your Godot Export Preset
